name: Build App and deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies ⬇️
      run: npm install
    # - name: Configure Firebase credentials
    - name: Generate build 🔧
      run: npm run build
      env:
        REACT_APP_API_KEY: ${{ secrets.API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.APP_ID }}
    # - name: Share artifact inside workflow
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: react-github-actions-build
    #     path: build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: build
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Get artifact
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: react-github-actions-build
  #     - name: Deploy to Heroku
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: "rent-progress"
  #         heroku_email: "v.sorokin@hey.com"
