name: Build App and deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies ⬇️
      run: npm install

    - name: Generate build 🔧
      run: npm run build
      env:
        REACT_APP_API_KEY: ${{ secrets.API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.APP_ID }}

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: .
